SCCPPGHA-6 Support Running on Linux ARM64
SonarSource/sonarcloud-github-c-cpp pull request #57
Opened 2024-05-24 13:34 UTC by enzo-pellegrini

List of checkpoint to verify/do before merging a PR.

### Dev checklist

* [ ] Write/update tests
* [ ] Functional validation
* [ ] Public documentation update
* [ ] Private documentation update
* [ ] Clean commits (should start with a ticket number, clear message, no fixup, wip)
* [ ] Maximize code coverage as much as possible

---

### Reviewer checklist

* [ ] Code review
* [ ] Functional validation
* [ ] Check commits are clean

---

### Steps to validate this PR

Fill-in how you performed the validation, and how the reviewer can replicate it:
* [ ]

2024-05-24 13:35 UTC, enzo-pellegrini commented
Currently there are [no github hosted linux arm64 runners](https://github.com/orgs/community/discussions/19197), which makes testing difficult,

2024-05-27 15:34 UTC, michael-jabbour-sonarsource commented on scripts/configure_paths.sh
> +if [[ ${ARCH} != "X64" && ! ( (${OS} == "macOS" && ${ARCH} == "ARM64") || (${OS} == "Linux" && ${ARCH} == "ARM64") ) ]]; then
A minor suggestion for simplification (untested)?

```suggestion
if [[ ${ARCH} != "X64" && ! (${ARCH} == "ARM64" && (${OS} == "macOS" || ${OS} == "Linux")) ]]; then 
```
WDYT?

2024-06-19 21:36 UTC, michael-jabbour-sonarsource commented on scripts/configure_paths.sh
> +if [[ ${ARCH} != "X64" && ! ( (${OS} == "macOS" && ${ARCH} == "ARM64") || (${OS} == "Linux" && ${ARCH} == "ARM64") ) ]]; then
I think I am missing something, you marked the conversation as resolved, and you kept the original version. Is my suggestion incorrect?

2024-06-19 21:44 UTC, enzo-pellegrini commented on scripts/configure_paths.sh
> +if [[ ${ARCH} != "X64" && ! ( (${OS} == "macOS" && ${ARCH} == "ARM64") || (${OS} == "Linux" && ${ARCH} == "ARM64") ) ]]; then
I committed your suggestion, I might have lost it in a force push while rebasing to have a single commit. sorry

2024-06-20 09:48 UTC, guillem-bartrina-sonarsource commented on scripts/configure_paths.sh
> +    esac
Just to comment something, within the two subcases you can define the variables in the same order as in the other cases to make it easier to read: 
1. SONAR_SCANNER_SUFFIX
2. BUILD_WRAPPER_SUFFIX
3. [SONAR_SCANNER_NAME] <-- no, because it is defined outside
4. BUILD_WRAPPER_NAME
5. SONAR_SCANNER_URL
6. SONAR_SCANNER_SHA

2024-06-20 09:50 UTC, guillem-bartrina-sonarsource commented on .github/workflows/tests.yml
> +          sonar-scanner --help | grep "usage: sonar-scanner "
Is it due to the version change?

2024-06-24 13:03 UTC, 7PH requested changes
I see that this pull request upgrades the sonar-scanner to v6, but the other PR does as well.

I think it is a good idea to separate the scanner bump in a different commit (as you did with the other PR), is it possible to split the work in 2 commits? (Could be in this PR or we can keep the other PR as well)

2024-06-24 13:40 UTC, 7PH approved these changes

2024-06-24 13:42 UTC, merged