Use native scanner
SonarSource/sonarcloud-github-c-cpp pull request #59
Opened 2024-06-27 08:21 UTC by enzo-pellegrini

List of checkpoint to verify/do before merging a PR.

### Dev checklist

* [ ] Write/update tests
* [ ] Functional validation
* [ ] Public documentation update
* [ ] Private documentation update
* [ ] Clean commits (should start with a ticket number, clear message, no fixup, wip)
* [ ] Maximize code coverage as much as possible

---

### Reviewer checklist

* [ ] Code review
* [ ] Functional validation
* [ ] Check commits are clean

---

### Steps to validate this PR

Fill-in how you performed the validation, and how the reviewer can replicate it:
* [ ]

2024-06-28 07:06 UTC, michael-jabbour-sonarsource commented on .github/workflows/tests.yml
> +      - name: check_runner_arch
(note: I find the solutions described above to be better than the `fromJSON` I mentioned yesterday)

2024-06-28 07:10 UTC, michael-jabbour-sonarsource requested changes
LGTM, I left one comment.

Have you validated this change by running analyses on Linux aarch64 using the current onboarding content?

2024-06-28 07:11 UTC, enzo-pellegrini commented on .github/workflows/tests.yml
> +      - name: check_runner_arch
Ah sorry I started hacking before reading this comment. I believe the solution I have just implemented to be the most easy and readable (simple if). LMKWYT

2024-06-28 07:43 UTC, michael-jabbour-sonarsource commented on .github/workflows/tests.yml
> +      - name: check_runner_arch
I think that it can also be simplified further: use ` - arch: X64` as a default and override it only for ` - macos-latest`. See the official example with ` - color: green` from my previous link.

2024-06-28 09:04 UTC, michael-jabbour-sonarsource commented on .github/workflows/tests.yml
> +      - name: check_runner_arch
Feel free to switch back to the more explicit version though if you prefer it...

2024-06-28 09:40 UTC, enzo-pellegrini commented
Validated [here](https://github.com/enzo-pellegrini/linux-autotools-gh-actions-sc/actions/runs/9710759349)

2024-06-30 19:04 UTC, michael-jabbour-sonarsource commented on action.yml
Would it make sense to add `runner.arch` to the cache key at this point? WDYT?

2024-07-01 15:15 UTC, michael-jabbour-sonarsource approved these changes
LGTM! Thanks for taking care of these changes. Could you ask AE for the final review before we merge?

2024-07-03 12:28 UTC, merged